-- INSERT INTO course (id, name, number, price) VALUES(1, 'course1', 10, 10000);
-- INSERT INTO course (id, name, number, price) VALUES(2, 'course1', 20, 15000);
-- INSERT INTO course (id, name, number, price) VALUES(3, 'course1', 30, 12000);
-- INSERT INTO course (id, name, number, price) VALUES(4, 'course1', 40, 6000);
-- INSERT INTO course (id, name, number, price) VALUES(5, 'course1', 50, 9000);
-- INSERT INTO course (id, name, number, price) VALUES(6, 'course1', 60, 10000);
-- INSERT INTO course (id, name, number, price) VALUES(7, 'course1', 70, 8000);
-- INSERT INTO course (id, name, number, price) VALUES(8, 'course1', 80, 16000);
--
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(1, 'Name1', 'Address1', 'Phone1', 'email1', 1001);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(2, 'Name2', 'Address2', 'Phone2', 'email2', 1002);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(3, 'Name3', 'Address3', 'Phone3', 'email3', 1003);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(4, 'Name4', 'Address4', 'Phone4', 'email4', 1004);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(5, 'Name5', 'Address5', 'Phone5', 'email5', 1005);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(6, 'Name6', 'Address6', 'Phone6', 'email6', 1006);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(7, 'Name7', 'Address7', 'Phone7', 'email7', 1007);
-- INSERT INTO student (id, name, address, phone, email, students_record_book_number) VALUES(8, 'Name8', 'Address8', 'Phone8', 'email8', 1008);
--
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(1, 'pname1', 'paddress1', 'pphone1', 10000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(2, 'pname2', 'paddress2', 'pphone2', 12000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(3, 'pname3', 'paddress3', 'pphone3', 8000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(4, 'pname4', 'paddress4', 'pphone4', 9000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(5, 'pname5', 'paddress5', 'pphone5', 12000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(6, 'pname6', 'paddress6', 'pphone6', 14000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(7, 'pname7', 'paddress7', 'pphone7', 14000);
-- INSERT INTO professor (id, name, address, phone, payment) VALUES(8, 'pname8', 'paddress8', 'pphone8', 8000);